language: python
python:
  - "3.6"
addons:
  chrome: stable
install:
  - wget -N https://chromedriver.storage.googleapis.com/85.0.4183.38/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - PATH=$PATH:~/
  - pip install -r requirements.txt
services:
  - postgresql
before_script:
  - psql -c 'create user root;'
  - psql -c 'ALTER USER root SUPERUSER;'
  - psql -c 'create database pur_beurre;'
script:
  - pytest
