language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
services:
  - postgresql
before_script:
  - psql -c 'create user root;'
  - psql -c 'create database pur_beurre;' -E utf8 -U root
script:
  - pytest


