language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
services:
  - postgresql
before_script:
  - psql -c 'create user root;'
  - psql -c 'ALTER USER root SUPERUSER;'
  - psql -c 'create database pur_beurre;'
addons:
  apt:
    update: true
    sources:
      - google-chrome
    packages:
      - dpkg
      - google-chrome-stable
script:
  - pytest


