language: python
python:
  - "3.6"
sudo: required
addons:
  chrome: stable
install:
  - pip install -r requirements.txt
services:
  - postgresql
before_script:
  - psql -c 'create user root;'
  - psql -c 'ALTER USER root SUPERUSER;'
  - psql -c 'create database pur_beurre;'
  - wget -N https://chromedriver.storage.googleapis.com/85.0.4183.87/chromedriver_linux64.zip -P ~/
  - mkdir webdriver
  - unzip ~/chromedriver_linux64.zip -d ~/webdriver
  - rm ~/chromedriver_linux64.zip
  - export PATH=$PATH:~/webdriver
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script:
  - pytest


