language: python
python:
  - "3.6"
sudo: required
addons:
  chrome: stable
install:
  - pip install -r requirements.txt
  - wget -N https://chromedriver.storage.googleapis.com/85.0.4183.87/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
services:
  - postgresql
before_script:
  - psql -c 'create user root;'
  - psql -c 'ALTER USER root SUPERUSER;'
  - psql -c 'create database pur_beurre;'
script:
  - pytest


