# Generated by Django 3.0.8 on 2020-09-03 09:36

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        UnaccentExtension(),
    ]
